#!/usr/bin/env python3
# Generate wt_luts.h: the wavetable engine's fixed-point lookup tables baked as
# const arrays, byte-for-byte identical to what wt_build_luts() computes at
# runtime. Lets the device skip pow/sin/cos at boot and drop the libm/soft-float
# dependency. Regenerate with:  python tools/gen_luts.py > wt_luts.h
#
# Correctness is enforced end-to-end: building wavetable.c.inl with
# -DWT_RUNTIME_LUTS recomputes the tables and the A/B render must stay bit-exact
# against the baked build.
import math, sys

def lround(x):
    # Match C lround: round to nearest, halfway away from zero.
    return math.floor(x + 0.5) if x >= 0 else math.ceil(x - 0.5)

def emit(out, ctype, name, vals, per_line):
    out.write(f"static const {ctype} {name}[{len(vals)}] = {{\n")
    for i in range(0, len(vals), per_line):
        chunk = vals[i:i+per_line]
        out.write("    " + ", ".join(str(v) for v in chunk) + ",\n")
    out.write("};\n\n")

def main():
    out = sys.stdout
    pow2 = [lround(math.pow(2.0, c/1200.0) * 65536.0) for c in range(1200)]
    pan_l, pan_r = [], []
    for p in range(128):
        a = p/127.0 * (math.pi*0.5)
        pan_l.append(lround(math.cos(a) * 32767.0))
        pan_r.append(lround(math.sin(a) * 32767.0))
    SIN = 1024
    sin_q = [lround(math.sin(2.0*math.pi*i/SIN) * 32767.0) for i in range(SIN)]
    cc = [lround((v*v)/(127.0*127.0) * 65536.0) for v in range(128)]

    out.write("// Generated by tools/gen_luts.py - do not edit by hand.\n")
    out.write("// Fixed-point LUTs for wavetable.c.inl (see gen_luts.py for the formulas).\n")
    out.write("#pragma once\n#include <stdint.h>\n\n")
    emit(out, "uint32_t", "g_pow2_cents_q16", pow2, 8)
    emit(out, "int16_t",  "g_pan_l_q15",      pan_l, 12)
    emit(out, "int16_t",  "g_pan_r_q15",      pan_r, 12)
    emit(out, "int16_t",  "g_sin_q15",        sin_q, 12)
    emit(out, "uint32_t", "g_cc_gain_q16",    cc, 8)

if __name__ == '__main__':
    main()
